# Generated by Django 3.0.5 on 2020-04-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollfordemo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
